name: 【测试】构建字体

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    name: 【测试】构建字体
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置环境
        run: |
          # 安装 Python 依赖
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

          # 安装构建依赖
          sudo apt-get update
          sudo apt-get install -y build-essential wget tar gzip

      - name: 编译字体
        run: |
          # 运行构建脚本
          bash build.bash

          # 验证输出文件
          if [ ! -f "output/xibo.psfu.gz" ]; then
            echo "错误：字体文件生成失败"
            exit 1
          fi

          # 显示文件信息
          ls -la output/xibo.psfu.gz

      - name: Upload artifact
        if: (cancelled() || failure() || success())
        uses: actions/upload-artifact@v4
        with:
          path: output/*
          compression-level: 9 # maximum compression
          retention-days: 5
